//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiveria.Common.Ensure {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnsureRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnsureRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tiveria.Common.Ensure.EnsureRes", typeof(EnsureRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empty collection not allowed. ähnelt.
        /// </summary>
        internal static string Ensure_IsEmptyCollection {
            get {
                return ResourceManager.GetString("Ensure_IsEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empty Guid not allowed. ähnelt.
        /// </summary>
        internal static string Ensure_IsEmptyGuid {
            get {
                return ResourceManager.GetString("Ensure_IsEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The param was expected to be a class, but was type of: &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotClass {
            get {
                return ResourceManager.GetString("Ensure_IsNotClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The param was expected to be a class, but was NULL. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotClass_WasNull {
            get {
                return ResourceManager.GetString("Ensure_IsNotClass_WasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected an expression that evaluates to false. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotFalse {
            get {
                return ResourceManager.GetString("Ensure_IsNotFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value &apos;{0}&apos; is not greater than limit &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotGt {
            get {
                return ResourceManager.GetString("Ensure_IsNotGt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value &apos;{0}&apos; is not greater than or equal to limit &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotGte {
            get {
                return ResourceManager.GetString("Ensure_IsNotGte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value &apos;{0}&apos; is &gt; max &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotInRange_ToHigh {
            get {
                return ResourceManager.GetString("Ensure_IsNotInRange_ToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The string is too long. Must be between &apos;{0}&apos; and  &apos;{1}&apos;. Must be between &apos;{0}&apos; and &apos;{1}&apos; but was &apos;{2}&apos; characters long. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotInRange_ToLong {
            get {
                return ResourceManager.GetString("Ensure_IsNotInRange_ToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value &apos;{0}&apos; is &lt; min &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotInRange_ToLow {
            get {
                return ResourceManager.GetString("Ensure_IsNotInRange_ToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The string is not long enough. Must be between &apos;{0}&apos; and &apos;{1}&apos; but was &apos;{2}&apos; characters long. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotInRange_ToShort {
            get {
                return ResourceManager.GetString("Ensure_IsNotInRange_ToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value &apos;{0}&apos; is not lower than limit &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotLt {
            get {
                return ResourceManager.GetString("Ensure_IsNotLt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value &apos;{0}&apos; is not lower than or equal to limit &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotLte {
            get {
                return ResourceManager.GetString("Ensure_IsNotLte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value can not be null. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotNull {
            get {
                return ResourceManager.GetString("Ensure_IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The string can&apos;t be null or empty. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Ensure_IsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The string can&apos;t be left empty, null or consist of only whitespaces. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Ensure_IsNotNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The param is not of expected type: &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotOfType {
            get {
                return ResourceManager.GetString("Ensure_IsNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected an expression that evaluates to true. ähnelt.
        /// </summary>
        internal static string Ensure_IsNotTrue {
            get {
                return ResourceManager.GetString("Ensure_IsNotTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value &apos;{0}&apos; does not match &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string Ensure_NoMatch {
            get {
                return ResourceManager.GetString("Ensure_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No MemberExpression found in expression: &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string ExpressionUtils_GetRightMostMember_NoMemberFound {
            get {
                return ResourceManager.GetString("ExpressionUtils_GetRightMostMember_NoMemberFound", resourceCulture);
            }
        }
    }
}
